name: Lint and Check

on:
  pull_request:
    branches:
      - main # もしくは対象とするデフォルトブランチ名（masterなど）

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22 # package.jsonの指定（>=22.12.0）に合わせてNode.jsのバージョンを設定します
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint
